name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven 3.9.5
      run: |
        wget https://downloads.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        tar -xvf apache-maven-3.9.5-bin.tar.gz
        sudo mv apache-maven-3.9.5 /opt/maven
        echo "M2_HOME=/opt/maven" >> $GITHUB_ENV
        echo "PATH=/opt/maven/bin:$PATH" >> $GITHUB_ENV
        export PATH=/opt/maven/bin:$PATH

    # Step 4: Verify Maven Version
    - name: Verify Maven Version
      run: mvn -version

    # Step 3: Increment Version
    - name: Increment Patch Version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        PATCH_VERSION=$(echo $VERSION | awk -F '.' '{print $1 "." $2 "." $3 + 1}')
        echo "New Version: $PATCH_VERSION"
        mvn versions:set -DnewVersion=$PATCH_VERSION
        mvn versions:commit

    # Step 4: Build JAR
    - name: Build JAR
      run: mvn clean package

    # Step 5: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t rotem1/simple-java-maven-app:${{ github.sha }} .

    # Step 6: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 7: Push Docker Image
    - name: Push Docker Image
      run: |
        docker push rotem1/simple-java-maven-app:${{ github.sha }}

    # Step 8: Deploy the Image (example: local Docker container)
    - name: Deploy Docker Container
      run: |
        docker run -d -p 8081:8080 rotem1/simple-java-maven-app:${{ github.sha }}

    - name: Fetch Logs
      run: docker logs $(docker ps -q --filter "ancestor=your-dockerhub-username/simple-java-maven-app:${{ github.sha }}")
