name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 3: Increment Version
    - name: Increment Patch Version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        PATCH_VERSION=$(echo $VERSION | awk -F '.' '{print $1 "." $2 "." $3 + 1}')
        echo "New Version: $PATCH_VERSION"
        mvn versions:set -DnewVersion=$PATCH_VERSION
        mvn versions:commit

    # Step 4: Build JAR
    - name: Build JAR
      run: mvn clean package

    # Step 5: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t your-dockerhub-username/simple-java-maven-app:${{ github.sha }} .

    # Step 6: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 7: Push Docker Image
    - name: Push Docker Image
      run: |
        docker push your-dockerhub-username/simple-java-maven-app:${{ github.sha }}

    # Step 8: Deploy the Image (example: local Docker container)
    - name: Deploy Docker Container
      run: |
        docker run -d -p 8080:8080 your-dockerhub-username/simple-java-maven-app:${{ github.sha }}
